# -*- coding: utf-8 -*-
"""CleanCodeKinshipIdentificationUsingSiameseNetwork.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ujIbgB-qshrAhuhcEX5qtwGCXp5W88jG
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install tensorflow

# Commented out IPython magic to ensure Python compatibility.
# %pip install keras

!pip install keras-tuner -q

import matplotlib.pyplot as plt
import numpy as np
import os
import random
import tensorflow as tf
from pathlib import Path
from tensorflow.keras import applications
from tensorflow.keras import layers
from tensorflow.keras import losses
from tensorflow.keras import optimizers
from tensorflow.keras import metrics
from tensorflow.keras import Model
from tensorflow.keras.applications import resnet
from tensorflow.keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
from PIL import Image
import keras_tuner as kt
from keras_tuner import RandomSearch, HyperParameters
from sklearn.metrics import f1_score
from sklearn.model_selection import KFold
from tensorflow.keras.backend import clear_session
import gc
from io import StringIO
import sys
import datetime
from matplotlib.backends.backend_pdf import PdfPages
target_shape = (200, 200)

!git config --global user.email "ppiedra90@gmail.com"
!git config --global user.name "ppiedra"
!git clone https://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@github.com/ppiedra/FIWDatabase.git

# Commented out IPython magic to ensure Python compatibility.
# %cd FIWDatabase
!git checkout testing
# %cd ..

cache_dir =  'FIWDatabase/train-facesAge30B1'
current_age =  'train-facesAge30B1'

def preprocess_image(filename):
    """
    Load the specified file as a JPEG image, preprocess it and
    resize it to the target shape.
    """
    image_string = tf.io.read_file(filename)
    image = tf.image.decode_jpeg(image_string, channels=3)
    image = tf.image.convert_image_dtype(image, tf.float32)
    image = tf.image.resize(image, target_shape)
    return image


def preprocess_triplets(anchor, positive, negative):
    """
    Given the filenames corresponding to the three images, load and
    preprocess them.
    """

    return (
        preprocess_image(anchor),
        preprocess_image(positive),
        preprocess_image(negative),
    )

#Code to load the images and transform them into triplets
# Count the amount of anchor photos
imageCount = 0

# Load the data
families = os.listdir(cache_dir)

#create the list to store all photos dirs
fatherImages = []
negativeMotherImages = []
kidsImages = []
motherImages = []
negativeFatherImages = []

# Iterate through families
for family in families:
    familyPhotos = os.listdir(os.path.join(cache_dir, family))

    # Count the amount of anchor photos
    for member in familyPhotos:
        memberPath = os.path.join(cache_dir, family, member)
        if member == "F":
            fatherPhotos = os.listdir(memberPath)
            imageCount += len(fatherPhotos)
            for dad in fatherPhotos:
                fatherImages.append(os.path.join(memberPath, dad))
        elif member == "NM":
            negativeMotherPhotos = os.listdir(memberPath)
            for negativeMom in negativeMotherPhotos:
                negativeMotherImages.append(os.path.join(memberPath, negativeMom))
        elif member == "NF":
            negativeDadPhotos = os.listdir(memberPath)
            for negativeDad in negativeDadPhotos:
                negativeFatherImages.append(os.path.join(memberPath, negativeDad))
        elif member == "M":
            motherPhotos = os.listdir(memberPath)
            for mom in motherPhotos:
                motherImages.append(os.path.join(memberPath, mom))
        elif member == "K":
            kidsPhotos = os.listdir(memberPath)
            for kid in kidsPhotos:
                kidsImages.append(os.path.join(memberPath, kid))

# All arrays are ready to be transformed FATHER
anchor_dataset = tf.data.Dataset.from_tensor_slices(fatherImages)
positive_dataset = tf.data.Dataset.from_tensor_slices(kidsImages)
negative_dataset = tf.data.Dataset.from_tensor_slices(negativeMotherImages)

# All arrays are ready to be transformed MOTHER
#anchor_dataset = tf.data.Dataset.from_tensor_slices(motherImages)
#positive_dataset = tf.data.Dataset.from_tensor_slices(kidsImages)
#negative_dataset = tf.data.Dataset.from_tensor_slices(negativeFatherImages)

# Load the auxiliary dataset with the triplets from each family
dataset = tf.data.Dataset.zip((anchor_dataset, positive_dataset, negative_dataset))
dataset = dataset.map(preprocess_triplets)

print(dataset)

# We need to make sure both the anchor and positive images are loaded in
# sorted order so we can match them together.

val_dataset_length = tf.data.experimental.cardinality(dataset).numpy()

print("Length of ALL dataset:", val_dataset_length)


# Let's now split our dataset in train and validation.
train_dataset = dataset.take(round(imageCount * 0.8))
val_dataset = dataset.skip(round(imageCount * 0.2))

train_dataset = train_dataset.batch(3, drop_remainder=False)
train_dataset = train_dataset.prefetch(8)

val_dataset = val_dataset.batch(3, drop_remainder=False)
val_dataset = val_dataset.prefetch(8)

train_length = tf.data.experimental.cardinality(train_dataset).numpy()
val_length = tf.data.experimental.cardinality(val_dataset).numpy()

print("Length of train_dataset:", train_length)
print("Length of val_dataset:", val_length)

def visualize(anchor, positive, negative):
    """Visualize a few triplets from the supplied batches."""

    def show(ax, image):
        ax.imshow(image)
        ax.get_xaxis().set_visible(False)
        ax.get_yaxis().set_visible(False)
    fig = plt.figure(figsize=(3, 3))

    axs = fig.subplots(3, 3)
    for i in range(3):
        show(axs[i, 0], anchor[i])
        show(axs[i, 1], positive[i])
        show(axs[i, 2], negative[i])

print("Training dataset")
print(train_dataset.take(1).as_numpy_iterator())
visualize(*list(train_dataset.take(1).as_numpy_iterator())[0])
print("Validation dataset")
visualize(*list(val_dataset.take(1).as_numpy_iterator())[0])

# Define the embedding model with hyperparameter tuning
def build_embedding_model(hp):
    base_cnn = resnet.ResNet50(
        weights="imagenet", input_shape=target_shape + (3,), include_top=False
    )
    x = base_cnn.output
    # Add tunable convolutional layers on top of the base model
    hp_conv_filters = hp.Int('conv_filters', min_value=32, max_value=256, step=32)
    x = layers.Conv2D(hp_conv_filters, (3, 3), activation=hp.Choice('conv_activation', values=['relu']))(x)
    x = layers.MaxPooling2D((2, 2))(x)
    x = layers.Conv2D(hp_conv_filters, (3, 3), activation=hp.Choice('conv_activation', values=['relu']))(x)
    x = layers.MaxPooling2D((2, 2))(x)

    #flatten = layers.Flatten()(x)
    flatten = layers.Flatten()(base_cnn.output)

    # Tune the number of units in the first Dense layer
    hp_unitsD1 = hp.Int('unitsD1', min_value=32, max_value=512, step=128)
    dense1 = layers.Dense(hp_unitsD1, activation=hp.Choice('conv_activation', values=['relu']))(flatten)
    dense1 = layers.BatchNormalization()(dense1)

    # Second Dense layer with fixed units
    hp_unitsD2 = hp.Int('unitsD2', min_value=32, max_value=256, step=128)
    dense2 = layers.Dense(hp_unitsD2, activation=hp.Choice('conv_activation', values=['relu']))(dense1)
    dense2 = layers.BatchNormalization()(dense2)

    # Output layer
    output = layers.Dense(256)(dense2)

    embedding = Model(base_cnn.input, output, name="Embedding")

    # Set trainable layers starting from 'conv5_block1_out'
    trainable = False
    for layer in base_cnn.layers:
        if layer.name == "conv5_block1_out":
            trainable = True
        layer.trainable = trainable

    return embedding

# Define the Siamese network model
def build_siamese_model(hp):
    embedding = build_embedding_model(hp)

    class DistanceLayer(layers.Layer):
        """
        This layer is responsible for computing the distance between the anchor
        embedding and the positive embedding, and the anchor embedding and the
        negative embedding.
        """
        def __init__(self, **kwargs):
            super().__init__(**kwargs)

        def call(self, anchor, positive, negative):
            ap_distance = tf.reduce_sum(tf.square(anchor - positive), -1)
            an_distance = tf.reduce_sum(tf.square(anchor - negative), -1)
            return (ap_distance, an_distance)

    anchor_input = layers.Input(name="anchor", shape=target_shape + (3,))
    positive_input = layers.Input(name="positive", shape=target_shape + (3,))
    negative_input = layers.Input(name="negative", shape=target_shape + (3,))

    distances = DistanceLayer()(
        embedding(resnet.preprocess_input(anchor_input)),
        embedding(resnet.preprocess_input(positive_input)),
        embedding(resnet.preprocess_input(negative_input)),
    )

    siamese_network = Model(
        inputs=[anchor_input, positive_input, negative_input], outputs=distances
    )

    class SiameseModel(Model):
        """The Siamese Network model with a custom training and testing loops.
        Computes the triplet loss using the three embeddings produced by the
        Siamese Network.
        The triplet loss is defined as:
           L(A, P, N) = max(‖f(A) - f(P)‖² - ‖f(A) - f(N)‖² + margin, 0)
        """
        def __init__(self, siamese_network, margin=0.5):
            super(SiameseModel, self).__init__()
            self.siamese_network = siamese_network
            self.margin = margin
            self.loss_tracker = metrics.Mean(name="loss")
            self.accuracy_tracker = metrics.Mean(name="accuracy")

        def call(self, inputs):
            return self.siamese_network(inputs)

        def train_step(self, data):
            with tf.GradientTape() as tape:
                loss = self._compute_loss(data)
                accuracy = self._compute_accuracy(data)

            gradients = tape.gradient(loss, self.siamese_network.trainable_weights)
            self.optimizer.apply_gradients(
                zip(gradients, self.siamese_network.trainable_weights)
            )

            self.loss_tracker.update_state(loss)
            self.accuracy_tracker.update_state(accuracy)
            return {"loss": self.loss_tracker.result(), "accuracy": self.accuracy_tracker.result()}

        def test_step(self, data):
            loss = self._compute_loss(data)
            accuracy = self._compute_accuracy(data)

            self.loss_tracker.update_state(loss)
            self.accuracy_tracker.update_state(accuracy)
            return {"loss": self.loss_tracker.result(), "accuracy": self.accuracy_tracker.result()}

        def _compute_loss(self, data):
            ap_distance, an_distance = self.siamese_network(data)
            loss = ap_distance - an_distance
            loss = tf.maximum(loss + self.margin, 0.0)
            return loss

        def _compute_accuracy(self, data):
            ap_distance, an_distance = self.siamese_network(data)
            return tf.reduce_mean(tf.cast(ap_distance < an_distance, tf.float32))

        @property
        def metrics(self):
            return [self.loss_tracker, self.accuracy_tracker]

    siamese_model = SiameseModel(siamese_network)
    siamese_model.compile(optimizer=optimizers.Adam(0.0001), metrics=['accuracy'])
    return siamese_model

# Commented out IPython magic to ensure Python compatibility.
# Convert the dataset to a list of numpy arrays for splitting
def dataset_to_numpy_list(dataset):
    return list(dataset.as_numpy_iterator())

# Convert dataset to list of triplets
triplet_list = dataset_to_numpy_list(dataset)

# Split the triplet list into anchors, positives, and negatives
anchors, positives, negatives = zip(*triplet_list)

# Convert lists to numpy arrays
anchors = np.array(anchors)
positives = np.array(positives)
negatives = np.array(negatives)

# Set the number of folds
kf = KFold(n_splits=5, shuffle=True, random_state=42)

# Initialize lists to store results for each fold
all_train_losses = []
all_val_losses = []
all_train_accuracies = []
all_val_accuracies = []
all_val_f1_scores = []
tuner_results_per_fold = []

# Variables to track the best hyperparameters across all folds
best_overall_hps = None
best_overall_score = -np.inf
best_fold = None
best_trial = None
# Generate a timestamp for the filename
timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
pdf_filename = f"fold_results_{current_age}_{timestamp}.pdf"

# Create a PDF file to store the results
with PdfPages(pdf_filename) as pdf:
    fold = 1

    for train_index, val_index in kf.split(anchors):
        # Clear previous session to free up GPU memory
        clear_session()
        gc.collect()

        print(f"Starting fold {fold}...")

        # Split the data into training and validation sets
        train_fold = tf.data.Dataset.from_tensor_slices(
            (anchors[train_index], positives[train_index], negatives[train_index])
        )
        val_fold = tf.data.Dataset.from_tensor_slices(
            (anchors[val_index], positives[val_index], negatives[val_index])
        )
        print("THIS IS TRAIN FOLD")
        print(train_fold)
        print("THIS IS VAL FOLD")
        print(val_fold)
        # Prefetch and batch the datasets
        train_fold = train_fold.batch(32).prefetch(tf.data.experimental.AUTOTUNE)
        val_fold = val_fold.batch(32).prefetch(tf.data.experimental.AUTOTUNE)

        # Capture the print output
        old_stdout = sys.stdout
        sys.stdout = mystdout = StringIO()

        # Define the model tuning for the current fold
        tuner = RandomSearch(
            build_siamese_model,  # Assuming build_siamese_model is defined elsewhere
            objective='val_accuracy',
            max_trials=3,  # Adjust based on your needs
            executions_per_trial=1,
            directory=f'my_dir_fold_{fold}',
            project_name=f'siamese_network_fold_{fold}'
        )

        # Perform the hyperparameter search on the current fold
        tuner.search(train_fold, epochs=15, validation_data=val_fold, verbose=1)

        # Restore the original stdout
        sys.stdout = old_stdout

        # Save the captured print output as a text string
        trial_logs = mystdout.getvalue()

        # Get the best hyperparameters for the current fold
        best_hps = tuner.get_best_hyperparameters(num_trials=1)[0]
        best_trial_score = tuner.oracle.get_best_trials(num_trials=1)[0].score

        # Check if this is the best overall score
        if best_trial_score > best_overall_score:
            best_overall_score = best_trial_score
            best_overall_hps = best_hps
            best_fold = fold
            best_trial = tuner.oracle.get_best_trials(num_trials=1)[0]

        # Store the tuner results for the current fold
        tuner_results_per_fold.append(tuner.oracle.get_best_trials(num_trials=1)[0])

        # Train the model with the best hyperparameters
        model = tuner.hypermodel.build(best_hps)
        history = model.fit(train_fold, epochs=15, validation_data=val_fold, verbose=1)

        # Store the history of losses and accuracies
        all_train_losses.append(history.history['loss'])
        all_val_losses.append(history.history['val_loss'])
        all_train_accuracies.append(history.history['accuracy'])
        all_val_accuracies.append(history.history['val_accuracy'])
        def evaluate_model(model, dataset, threshold=0.5):
            y_true = []
            y_pred = []
            for batch in dataset:
                # The batch will contain triplets of (anchor, positive, negative)
                anchor, positive, negative = batch

                # Predict for the batch (multiple triplets)
                results = model.predict([anchor, positive, negative])

                # `results` is a tuple of (ap_distance, an_distance)
                ap_distance, an_distance = results

                # Iterate over the batch to compute true and predicted labels
                for i in range(len(ap_distance)):
                    # True label for positive pair (anchor-positive)
                    y_true.append(1)  # Positive pair (kinship exists)
                    # Predict: 1 if the anchor-positive distance is below the threshold
                    y_pred.append(int(ap_distance[i] < threshold))

                    # True label for negative pair (anchor-negative)
                    y_true.append(0)  # Negative pair (no kinship)
                    # Predict: 0 if the anchor-negative distance is above the threshold
                    y_pred.append(int(an_distance[i] > threshold))

            # Calculate the F1-Score based on y_true and y_pred
            f1 = f1_score(y_true, y_pred)
            return f1

        f1 = evaluate_model(model, val_fold)
        all_val_f1_scores.append(f1)
        print(f"Validation F1-Score for fold {fold}: {f1}")
        #Save the F1_Scroe peer fold
        plt.figure()
        plt.text(0.1, 0.8, f'Validation F1-Score for fold {fold}: {f1}', fontsize=12)
        plt.text(0.1, 0.7, f'{f1}', fontsize=10)
        plt.axis('off')
        pdf.savefig()  # Save the fold F1-Score on the PDF
        plt.close()

        # Save the results for this fold to the PDF
        def plot_fold_results(train_data, val_data, metric_name, fold_number):
            plt.figure()
            plt.plot(train_data, label=f'Training {metric_name} Fold {fold_number}')
            plt.plot(val_data, label=f'Validation {metric_name} Fold {fold_number}')
            plt.title(f'Training and Validation {metric_name} for Fold {fold_number}')
            plt.xlabel('Epoch')
            plt.ylabel(metric_name)
            plt.legend()
            pdf.savefig()  # Save the current figure to the PDF
            plt.close()

        plot_fold_results(history.history['loss'], history.history['val_loss'], 'Loss', fold)
        plot_fold_results(history.history['accuracy'], history.history['val_accuracy'], 'Accuracy', fold)

        # Add text output for the best hyperparameters, trial score, and captured logs
        plt.figure()
        plt.text(0.1, 0.8, f'Best Hyperparameters for Fold {fold}:', fontsize=12)
        plt.text(0.1, 0.7, f'{tuner_results_per_fold[-1].hyperparameters.values}', fontsize=10)
        plt.text(0.1, 0.6, f'Best Trial Score for Fold {fold}: {tuner_results_per_fold[-1].score}', fontsize=10)
        plt.axis('off')
        pdf.savefig()  # Save the current text to the PDF
        plt.close()

        # Save the trial logs as text to the PDF
        plt.figure(figsize=(8, 12))
        plt.text(0.01, 0.99, trial_logs, fontsize=8, verticalalignment='top', wrap=True)
        plt.axis('off')
        pdf.savefig()  # Save the captured trial logs to the PDF
        plt.close()

        fold += 1

    # Calculate averages across all folds
    average_val_f1_score = np.mean(all_val_f1_scores)
    average_val_loss = np.mean([np.mean(val_loss) for val_loss in all_val_losses])
    average_val_accuracy = np.mean([np.mean(val_acc) for val_acc in all_val_accuracies])

    print(f"Average Validation F1-Score across all folds: {average_val_f1_score}")
    print(f"Average Validation MSE across all folds: {average_val_loss}")
    print(f"Average Validation Accuracy across all folds: {average_val_accuracy}")

    # Add the averages to the PDF
    plt.figure()
    plt.text(0.1, 0.8, f'Average Validation F1-Score across all folds:', fontsize=12)
    plt.text(0.1, 0.7, f'{average_val_f1_score}', fontsize=10)
    plt.text(0.1, 0.6, f'Average Validation MSE across all folds:', fontsize=12)
    plt.text(0.1, 0.5, f'{average_val_loss}', fontsize=10)
    plt.text(0.1, 0.4, f'Average Validation Accuracy across all folds:', fontsize=12)
    plt.text(0.1, 0.3, f'{average_val_accuracy}', fontsize=10)
    plt.axis('off')
    pdf.savefig()  # Save the average metrics text to the PDF
    plt.close()

    # Add the best overall hyperparameters and fold information to the PDF
    plt.figure()
    plt.text(0.1, 0.8, f'Best Hyperparameters Found:', fontsize=12)
    plt.text(0.1, 0.7, f'Best Fold: {best_fold}', fontsize=10)
    plt.text(0.1, 0.6, f'Best Trial Score: {best_overall_score}', fontsize=10)
    plt.text(0.1, 0.5, f'Best Hyperparameters: {best_overall_hps.values}', fontsize=10)
    plt.axis('off')
    pdf.savefig()  # Save the best overall hyperparameters to the PDF
    plt.close()
    #save pdf on git
    print(pdf_filename)
    !cp $pdf_filename FIWDatabase/FinalReports/
#     %cd FIWDatabase
    !git add .
    !git commit -m "Add $pdf_filename from Colab"
    !git push origin testing
#     %cd ..